import { Language, Level, topics } from "./practice";

// Additional authored prompts keep each topic and level fresh while retaining
// complete, word-by-word glosses for the feedback vocabulary.
type ExtraSentence = [english: string, target: string, glosses: string];
const german: Record<Level, ExtraSentence[][]> = {
  A1: [
    [["I make my bed in the morning.","Ich mache morgens mein Bett.","I|make|in the morning|my|bed"],["The kitchen is clean.","Die Küche ist sauber.","the|kitchen|is|clean"],["I drink water with lunch.","Ich trinke Wasser zum Mittagessen.","I|drink|water|with the|lunch"],["The bus comes at nine.","Der Bus kommt um neun.","the|bus|comes|at|nine"],["My cousin has a new job.","Mein Cousin hat eine neue Arbeit.","my|cousin|has|a|new|job"],["I read a short story.","Ich lese eine kurze Geschichte.","I|read|a|short|story"]],
  ],
  A2: [
    [["I left my keys on the table.","Ich habe meine Schlüssel auf dem Tisch liegen lassen.","I|have|my|keys|on|the|table|lying|left"],["We found a quiet hotel near the river.","Wir haben ein ruhiges Hotel in der Nähe des Flusses gefunden.","we|have|a|quiet|hotel|in|the|vicinity|of the|river|found"],["Could I have the menu, please?","Könnte ich bitte die Speisekarte bekommen?","could|I|please|the|menu|get"],["She takes notes during the lesson.","Sie macht während des Unterrichts Notizen.","she|makes|during|the|lesson|notes"],["I called my parents on Sunday.","Ich habe meine Eltern am Sonntag angerufen.","I|have|my|parents|on|Sunday|called"],["This game is easier than the last one.","Dieses Spiel ist leichter als das letzte.","this|game|is|easier|than|the|last"]],
  ],
  B1: [
    [["I try to cook at home more often.","Ich versuche, öfter zu Hause zu kochen.","I|try|more often|at|home|to|cook"],["We changed our plans at the last minute.","Wir haben unsere Pläne im letzten Moment geändert.","we|have|our|plans|at the|last|moment|changed"],["Could you tell me whether this dish contains nuts?","Könnten Sie mir sagen, ob dieses Gericht Nüsse enthält?","could|you|to me|say|whether|this|dish|nuts|contains"],["I have been waiting for the delivery since Tuesday.","Ich warte seit Dienstag auf die Lieferung.","I|wait|since|Tuesday|for|the|delivery"],["My aunt taught me how to play the guitar.","Meine Tante hat mir beigebracht, Gitarre zu spielen.","my|aunt|has|to me|taught|guitar|to|play"],["I enjoy books that make me think.","Ich mag Bücher, die mich zum Nachdenken bringen.","I|like|books|that|me|to|thinking|bring"]],
  ],
  B2: [
    [["A flexible schedule makes it easier to balance work and family.","Ein flexibler Zeitplan erleichtert es, Arbeit und Familie zu vereinbaren.","a|flexible|schedule|makes easier|it|work|and|family|to|reconcile"],["The regional train was cancelled without warning.","Der Regionalzug wurde ohne Vorwarnung gestrichen.","the|regional train|was|without|warning|cancelled"],["The chef uses seasonal produce whenever possible.","Der Koch verwendet möglichst saisonale Zutaten.","the|chef|uses|as much as possible|seasonal|ingredients"],["Although the meeting ran late, we covered every item.","Obwohl die Besprechung länger dauerte, behandelten wir jeden Punkt.","although|the|meeting|longer|lasted|we|covered|every|item"],["She keeps in touch with friends she met abroad.","Sie hält Kontakt zu Freunden, die sie im Ausland kennengelernt hat.","she|keeps|contact|with|friends|whom|she|in the|foreign country|met|has (past tense helper)"],["I would support the plan if its costs were transparent.","Ich würde den Plan unterstützen, wenn seine Kosten transparent wären.","I|would|the|plan|support|if|its|costs|transparent|were"]],
  ],
  C1: [
    [["A consistent routine can make daily responsibilities feel manageable.","Ein beständiger Tagesablauf kann alltägliche Aufgaben bewältigbar erscheinen lassen.","a|consistent|daily routine|can|everyday|responsibilities|manageable|appear|make"],["The delay prompted us to reconsider our route.","Die Verzögerung veranlasste uns, unsere Route zu überdenken.","the|delay|prompted|us|our|route|to|reconsider"],["The menu reflects the region's agricultural traditions.","Die Speisekarte spiegelt die landwirtschaftlichen Traditionen der Region wider.","the|menu|reflects (with wider)|the|agricultural|traditions|of the|region|back (with spiegelt: reflects)"],["Clear expectations help teams work independently.","Klare Erwartungen helfen Teams, selbstständig zu arbeiten.","clear|expectations|help|teams|independently|to|work"],["She described how moving abroad reshaped her sense of home.","Sie beschrieb, wie der Umzug ins Ausland ihr Heimatgefühl verändert hat.","she|described|how|the|move|to the|foreign country|her|sense of home|changed|has (past tense helper)"],["The evidence remains inconclusive despite extensive research.","Die Belege bleiben trotz umfangreicher Forschung uneindeutig.","the|evidence|remain|despite|extensive|research|inconclusive"]],
  ],
  C2: [
    [["Domestic rituals provide stability amid constant change.","Häusliche Rituale bieten inmitten ständigen Wandels Stabilität.","domestic|rituals|provide|amid|constant|change|stability"],["The itinerary was revised in light of new restrictions.","Die Reiseroute wurde angesichts neuer Einschränkungen überarbeitet.","the|itinerary|was|in light of|new|restrictions|revised"],["A dish's simplicity can foreground the quality of its ingredients.","Die Schlichtheit eines Gerichts kann die Qualität seiner Zutaten hervorheben.","the|simplicity|of a|dish|can|the|quality|of its|ingredients|foreground"],["The policy's success hinges on consistent implementation.","Der Erfolg der Richtlinie hängt von einer konsequenten Umsetzung ab.","the|success|of the|policy|depends (with ab)|on|a|consistent|implementation|away (with h?ngt: depends on)"],["Social ties often endure beyond the circumstances that formed them.","Soziale Bindungen bestehen oft über die Umstände hinaus, durch die sie entstanden sind.","social|ties|endure|often|beyond (with hinaus)|the|circumstances|beyond (with ?ber)|through|which|they|arisen|have (past tense helper)"],["Her argument acknowledges uncertainty without surrendering its central claim.","Ihr Argument erkennt Unsicherheit an, ohne seine zentrale These aufzugeben.","her|argument|acknowledges (with an)|uncertainty|on (with erkennt: acknowledges)|without|its|central|claim|giving up"]],
  ],
};

const chinese: Record<Level, ExtraSentence[][]> = {
  A1: [
    [["I eat breakfast at home.","Wǒ zài jiā chī zǎofàn.","I|at|home|eat|breakfast"],["My room is very small.","Wǒ de fángjiān hěn xiǎo.","I|possessive particle|room|very|small"],["I want hot tea.","Wǒ xiǎng hē rè chá.","I|want|drink|hot|tea"],["Where can I buy a ticket?","Wǒ zài nǎlǐ mǎi piào?","I|at|where|buy|ticket"],["My older sister works here.","Wǒ jiějie zài zhèlǐ gōngzuò.","I|older sister|at|here|works"],["This song is nice.","Zhè shǒu gē hěn hǎotīng.","this|measure word for songs|song|very|pleasant to listen to"]],
  ],
  A2: [
    [["I cleaned the kitchen yesterday.","Zuótiān wǒ dǎsǎo le chúfáng.","yesterday|I|clean|completed action particle|kitchen"],["We are going to the airport by bus.","Wǒmen zuò gōnggòng qìchē qù jīchǎng.","we|take|public|bus|go to|airport"],["Could I have a little more rice?","Qǐng zài gěi wǒ yìdiǎn mǐfàn, kěyǐ ma?","please|again|give|me|a little|rice|may|question particle"],["She studies Chinese after work.","Tā xiàbān yǐhòu xué Zhōngwén.","she|finish work|after|studies|Chinese"],["I forgot to bring my umbrella.","Wǒ wàng le dài sǎn.","I|forgot|completed action particle|bring|umbrella"],["This route is faster than the other one.","Zhè tiáo lù bǐ nà tiáo kuài.","this|measure word for roads|road|compared with|that|measure word|fast"]],
  ],
  B1: [
    [["I try to exercise several times a week.","Wǒ jǐnliàng měi zhōu duō yùndòng jǐ cì.","I|try to|every|week|more|exercise|several|times"],["We changed our plans at the last minute.","Wǒmen zuìhòu yí kè gǎibiàn le jìhuà.","we|last|one|moment|changed|completed action particle|plans"],["Could you tell me whether this dish contains peanuts?","Nǐ néng gàosu wǒ zhè dào cài yǒu méiyǒu huāshēng ma?","you|can|tell|me|this|measure word for dishes|dish|has|does not have (with y?u: whether it has)|peanuts|question particle"],["I have been waiting for the package since Tuesday.","Wǒ cóng Xīngqī'èr kāishǐ yìzhí zài děng kuàidì.","I|from|Tuesday|start|continuously|at|wait|parcel"],["My aunt taught me how to make dumplings.","Wǒ āyí jiāo huì le wǒ bāo jiǎozi.","my|aunt|teach|learned|completed action particle|me|wrap|dumplings"],["I enjoy books that make me think.","Wǒ xǐhuan nàxiē ràng wǒ sīkǎo de shū.","I|like|those|make|me|think|descriptive particle|books"]],
  ],
  B2: [
    [["A flexible schedule makes it easier to balance work and family.","Línghuó de shíjiān ānpái ràng rén gèng róngyì jiāngù gōngzuò hé jiātíng.","flexible|descriptive particle|time|arrangement|makes|people|more|easy|balance|work|and|family"],["The regional train was cancelled without warning.","Qūyù lièchē háo wú yùjǐng de qǔxiāo le.","regional|train|without|any|warning|manner particle|cancelled|completed action particle"],["The chef uses seasonal ingredients whenever possible.","Chúshī jǐn kěnéng shǐyòng dāngjì shícái.","chef|as much as (with k?n?ng)|possible|use|current season|ingredients"],["Although the meeting ran late, we covered every item.","Suīrán huìyì tuōyán le, wǒmen háishi tǎolùn le měi ge yìtí.","although|meeting|ran late|completed action particle|we|still|discussed|completed action particle|every|measure word|topic"],["She stays in touch with friends she met abroad.","Tā yìzhí hé zài guówài rènshi de péngyou bǎochí liánxì.","she|continues to|with|in|foreign country|met|descriptive particle|friends|maintain|contact"],["I would support the plan if its costs were transparent.","Rúguǒ fèiyòng tòumíng, wǒ huì zhīchí zhège jìhuà.","if|costs|transparent|I|would|support|this|plan"]],
  ],
  C1: [
    [["A steady routine can make daily responsibilities feel manageable.","Wěndìng de rìcháng ānpái néng ràng měitiān de zérèn biànde róngyì yìngduì.","stable|descriptive particle|daily|arrangement|can|make|every day|descriptive particle|responsibilities|become|easy|to handle"],["The delay prompted us to reconsider our route.","Zhè cì yánwù cùshǐ wǒmen chóngxīn kǎolǜ lùxiàn.","this|measure word for events|delay|prompted|us|again|consider|route"],["The menu reflects the region's farming traditions.","Càidān tǐxiàn le zhège dìqū de nóngyè chuántǒng.","menu|reflects|completed action particle|this|region|descriptive particle|agricultural|traditions"],["Clear expectations help teams work independently.","Míngquè de qīdài yǒuzhù yú tuánduì dúlì gōngzuò.","clear|descriptive particle|expectations|help (with y?)|to (with y?uzh?)|teams|independently|work"],["She described how moving abroad changed her sense of home.","Tā jiǎngshù le yíjū guówài rúhé gǎibiàn le tā duì jiā de gǎnshòu.","she|described|completed action particle|moving|abroad|how|changed|completed action particle|her|toward|home|descriptive particle|feeling"],["The evidence remains inconclusive despite extensive research.","Jǐnguǎn jìnxíng le dàliàng yánjiū, zhèngjù réngrán méiyǒu dìnglùn.","despite|conducted|completed action particle|extensive|research|evidence|still|has no|conclusion"]],
  ],
  C2: [
    [["Domestic rituals provide stability amid constant change.","Jiātíng yíshì zài chíxù biànhuà zhōng dàilái wěndìng gǎn.","domestic|rituals|in (with zh?ng: amid)|continuous|change|amid (with z?i)|bring|stability|sense"],["The itinerary was revised in light of new restrictions.","Jiànyú xīn de xiànzhì, xíngchéng zuò le tiáozhěng.","in view of|new|descriptive particle|restrictions|itinerary|made|completed action particle|adjustment"],["A dish's simplicity can highlight the quality of its ingredients.","Yí dào cài de jiǎnyuē fēnggé fǎn'ér néng tūxiǎn shícái de pǐnzhì.","one|measure word|dish|descriptive particle|simple|minimal style|instead|can|highlight|ingredients|descriptive particle|quality"],["The policy's success depends on consistent implementation.","Zhè xiàng zhèngcè néngfǒu chénggōng qǔjué yú shìfǒu yíguàn luòshí.","this|measure word|policy|whether it can|succeed|depends (with y?)|on (with q?ju?)|whether|consistently|implement"],["Social ties often endure beyond the circumstances that formed them.","Rénjì guānxì wǎngwǎng chāoyuè le zuìchū xíngchéng tāmen de huánjìng.","social|relations|often|go beyond|completed action particle|initially|formed|them|descriptive particle|circumstances"],["Her argument recognizes uncertainty without giving up its central claim.","Tā de lùnzhèng chéngrèn bù quèdìngxìng, què méiyǒu fàngqì héxīn zhǔzhāng.","her|descriptive particle|argument|acknowledges|not (with qu?d?ngx?ng: uncertainty)|certainty|but|not|give up|central|claim"]],
  ],
};

export function extraSentenceRows(language: Language, level: Level, topic: string): ExtraSentence[] {
  const topicIndex = topics.indexOf(topic as (typeof topics)[number]);
  const rows = (language === "chinese" ? chinese : german)[level][0];
  return rows?.[topicIndex] ? [rows[topicIndex]] : [];
}
